### ISSUE TITLE
Cleanup/Simplify API (and make it more flexible)

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#127]
We currently have the following endpoints in the API - 

```
  GET /v1/chain/:id
  GET /v1/chain/utxo/:id
  GET /v1/pool/:id
  POST /v1/pool/push
```

And the following endpoints on the wallet API - 

```
  POST /v1/receive/coinbase
  POST /v1/receive/receive_json_tx
```

Note: the `:id` url param is actually redundant in both `/v1/chain/:id` and `/v1/pool/:id` but is there as an artifact of the `ApiEndpoint` implementation.

Ideally these endpoints would be implemented not as `get` on a collection of resources but as `get` (or `index`) on a single resource.

```
  GET /v1/chain
  GET /v1/chain/utxo/:id
  GET /v1/pool
  POST /v1/pool/push
```

While these API endpoints are RESTful (with some custom operations) they are not really CRUD - we do not currently have much need for full `DELETE/GET/POST/PUT` support.

Additionally it may be desirable to support `GET /` endpoints for single resources to avoid the redundant `:id` url param.

We may also want to return multiple utxos when checking the wallet to avoid an API call per utxo. 
We could do this to query/filter by multiple ids on the `index` endpoint -

```
  GET /v1/chain/utxo?ids=1,2,3`
```

This is not currently supported in the existing API framework.

I'm wondering if it may make sense to attempt to simplify the API by eliminating the intermediate `ApiEndpoint` framework and implement each specific endpoint directly via an Iron route handler.
I think this would remove a lot of code while making it more flexible (query/filter by ids etc.)

Thoughts on this? Is it worth seeing what the API code looks like with this approach?

**Comment by ignopeverell** [comment]
It may be worth trying it out if you think the approach could work better. The idea behind the `ApiEndpoint` was actually to reduce the amount of code in the longer term. Right now we only have a few endpoints, but I'm expecting we'll eventually end up with quite a bit (just look at bitcoind or geth), some being of the CRUD family (push transactions, maybe some bloom filter of outputs one would be interested in, etc).

The chain/:id should get used I think, it's meant to differentiate between the mainnet and the different testnets (so could be chain/main, chain/test1, chain/testN). Does that make sense?

**Comment by antiochp** [comment]
Yeah makes sense. I'm playing around with the wallet endpoints directly in Iron with no ApiEndpoint intermediate layer.
It it looks worth pursuing I'll put a PR up - but I'm not 100% convinced it will be an improvement.

**Comment by antiochp** [comment]
Closing - still thinking about this.
