### ISSUE TITLE
Setup a mailing list

### ISSUE THREAD

**Issue by ignopeverell** [ignopeverell/grin#13]
Long pull requests conversations quickly break down... Anyone knows of a good mailing list service that doesn't require a phone-bound account (i.e. google groups) and isn't too hostile to Tor?

/cc @GarrickOllivander @merope07 @apoelstra

**Comment by apoelstra** [comment]
I'm not aware of any but I've put a feeler out on IRC. I can probably host something on wpsoftware.net if it comes to it.

**Comment by ignopeverell** [comment]
Thanks! In the absence of a better solution I was thinking of going for either savannah.nongnu.org or sourceforge. Or maybe Hyperledger (joking).

**Comment by apoelstra** [comment]
savannah.nongnu.org sounds good. I have a strong aversion to Sourceforge after they were found bundling malware into binaries other people were hosting there.

**Comment by ignopeverell** [comment]
As an update, it looks like @apoelstra may be able to get us a Linux Foundation mailing list.

**Comment by ignopeverell** [comment]
As the other plans don't seem to be coming through, I created a team with an associated mailing list on Launchpad:

https://launchpad.net/~mimblewimble

Requires a simple registration, add yourself to the team and subscribe to the list. @merope07 and @GarrickOllivander I'd love to have you there.
