### ISSUE TITLE
Configurable Coinbase Maturity (based on mining parameter mode)

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#133]
The docs (somewhere) suggest a value of `1_000` for `COINBASE_MATURITY`.
This is based on a 1 minute block time (vs. Bitcoin with 10 min block time and coinbase maturity of 100 blocks). 

This makes testing of nodes and wallets _really_ difficult as we need to wait for 1_000 blocks before anything becomes spendable.

We have temporarily reduced this in consensus.rs -
https://github.com/ignopeverell/grin/blob/a5b2c7d3f2d057666a33e416ebf068722a7af6c2/core/src/consensus.rs#L32

Ideally we can make this configurable somehow - possibly based on `mining_parameter_mode` in `grin.toml` 

```
mining_parameter_mode = "UserTesting"
```

Proposed values - 
* AutomatedTesting - `COINBASE_MATURITY=3`
* UserTesting - `COINBASE_MATURITY=3`
* Production - `COINBASE_ MATURITY=1_000`

We also need to make sure this is documented somewhere in the docs (and not just this and other issues).

**Comment by ignopeverell** [comment]
@yeastplume has created a module to handle static globals like these that we may still need to change for testing or different networks. Check core/src/global.rs.

**Comment by yeastplume** [comment]
I'll add this to global.rs shortly, as I think it's desirable to have in advance of the testnet.

**Comment by yeastplume** [comment]
done, this can be closed
