### ISSUE TITLE
How does a miner collect txn fees?

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#135]
A spends `amount=100` to send `amount=50` to B with additional txn fee `amount=1` (sending total `amount=51`).
A receives change `amount=49`.
B receives `amount=50`.
Miner receives `amount=1000000` for mining the block.
The fee`amount=1` effectively gets burned and is now unspendable? There is no output created that represents this value.

What is the intended mechanics of getting this `amount=1` into the miners wallet in a spendable way?

I'm assuming it either needs to be - 
1) a new output with corresponding kernel signed by the miners wallet key, or
2) added to the existing coinbase output somehow

Or am I missing something here?

**Comment by ignopeverell** [comment]
Right now it gets burnt, that's part of my original design where fees are strictly for spam prevention and aren't awarded to miners. But it's probably the most controversial part of that design. There's been a lot of discussion on this on gitter but we should probably settle that on the mailing-list once and for all.

**Comment by antiochp** [comment]
Ahh - makes sense now.
I was assuming this had just not been implemented yet.
For the sake of my curiosity - if "miners collect fees" _were_ to be implemented how would this be done - would we add the fee to the coinbase and handle it with a single output? Or would we need a separate output to handle fees?

**Comment by antiochp** [comment]
Closing this for now.
