### ISSUE TITLE
master not compiling on macOS

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#144]
```
error[E0425]: cannot find function `ftruncate64` in module `libc`
   --> store/src/sumtree.rs:141:28
    |
141 | 		let res = unsafe { libc::ftruncate64(fd, offs as i64) };
    | 		                         ^^^^^^^^^^^ did you mean `ftruncate`?

error: aborting due to previous error

error: Could not compile `grin_store`.
```

Looks like `libc` supports `ftruncate64` on `/unix/notbsd` - 
https://github.com/rust-lang/libc/blob/e4f8ab82bc94c8609a42aed80d5ef991bfcfa416/src/unix/notbsd/mod.rs#L913

But `ftruncate` on the more generic `/unix` (including macos) - 
https://github.com/rust-lang/libc/blob/209468a67345caba39b6d40fd6f08efed68106ef/src/unix/mod.rs#L561

**Comment by yeastplume** [comment]
Yep, confim getting this as well on OSX

**Comment by antiochp** [comment]
Some discussion here around conditional compilation (and runtime decisions) https://internals.rust-lang.org/t/feature-based-conditional-compilation/4533/3

**Comment by quentinlesceller** [comment]
Why not use ftruncate instead of ftruncate64?

**Comment by yeastplume** [comment]
It's easy enough to kludge in a fix via conditional compilation, however features are intentionally limited in scope (they only cover the next statement), cause it's much more 'Rust' to try and avoid all sorts of #if this that and the other all over the code depending on platform. That's an unsafe function however, so just setting it to ftruncate could cause subtle issues on other platforms.

**Comment by ignopeverell** [comment]
Had to add platform specific imports. I can't test on MacOS so please tell me if that didn't fix it.

**Comment by antiochp** [comment]
:+1: just tested locally against master and it build happily on MacOS.
