### ISSUE TITLE
cuckoo_miner not compiling on macOS

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#152]
This is on macOS Sierra 10.12.6
Command line tools were updated recently (version 9.0) and I suspect this is related.

```
/Library/Developer/CommandLineTools/usr/include/c++/v1/__threading_support:156:1: error: unknown type name 'mach_port_t'
mach_port_t __libcpp_thread_get_port();
```

https://gist.github.com/antiochp/ffbc210f3c9cc41dd9c3612c0a619d37

**Comment by yeastplume** [comment]
I could fix this in our branch, but to this actually needs to be fixed within @tromp's repository, so I've opened an issue there.

**Comment by oriste** [comment]
just FYI I pulled the latest grin from github just now (79 files changed, 4624 insertions(+), 3242 deletions(-)) and compiled on my early 2011 MBP macOS 10.13 with rustc rustc 1.20.0 (f3d6973f4 2017-08-27). No problems. Running the advanced example now.

**Comment by yeastplume** [comment]
Managed to reproduce and fix. Will PR once John's finished another few unrelated fixes to one of the miners.

**Comment by yeastplume** [comment]
@antiochp can you test as well, just to be sure so this can be closed?

**Comment by oriste** [comment]
Let me know if I can help here.

**Comment by antiochp** [comment]
:+1: I can build successfully here on macOS - so I think we're good.
