### ISSUE TITLE
wallet appending duplicate coinbase outputs from miner

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#157]
The "ask for a new coinbase if the block fees change" appears to have introduced a bug in the way the wallet tracks outputs.
The wallet is always appending the output to its internal list, regardless of if the coinbase is actually new (or just rebuilt because the fees may have changed).

```
Outputs - 
fingerprint, n_child, height, lock_height, status, value
----------------------------------
fd997546, 1, 1, 4, Immature, 1000000000
15d2f09b, 2, 2, 5, Immature, 1000000000
6040547d, 3, 0, 0, Unconfirmed, 1000000000
6040547d, 3, 0, 0, Unconfirmed, 1000000000
```

Fix coming shortly - I think the wallet just need to check to existing outputs before appending a new one.
I'm also playing around with passing the `pubkey` to the miner and not the `derivation` when we build the coinbase - I think we can keep the `derivation` internal to the wallet/keychain and not need to leak it outside.

**Comment by antiochp** [comment]
Actually we always want the latest version of a coinbase output - to ensure the updated fees are correctly handled.
So we want to overwrite in this case.

**Comment by ignopeverell** [comment]
Correct, I missed it was going to keep appending anyway. Thanks for looking into it!

**Comment by antiochp** [comment]
Just pushed up #158 to fix this - went a bit deeper than I intended but I think the wallet is in a better place now.
Spent a couple of hours really battling against the borrowchecker trying to get the vec of outputs in the wallets updated (either appended or updated in place...)
Ended up reworking it to use a HashMap (which is hopefully closer to what we want anyway).
