### ISSUE TITLE
sort inputs/outputs lexicographically during serialization

### ISSUE THREAD

**Issue by antiochp** [ignopeverell/grin#168]
I know we're doing it in some places (we sort in a couple of places for inputs/outputs in blocks).

But we should make sure we sort before we serialize (specifically for transactions, but presumably for blocks also).
This is relatively low-hanging fruit.

From @apoelstra in gitter - 
> it occurs to me that even on the wire, transaction inputs and outputs should be lexicographically ordered.. one big privacy leak in bitcoin is wallet fingerprinting, we should try to make transactions as unique as possible

https://gitter.im/grin_community/Lobby?at=59dcc0d4210ac26920cb02f7

**Comment by apoelstra** [comment]
To clarify, I think it should be a consensus rule that everything on the wire is sorted (and everything in blocks should be). This is super cheap to verify and will prevent broken software.

**Comment by antiochp** [comment]
Ah right - of course, we can actually verify this via a consensus rule...

**Comment by antiochp** [comment]
Resolved in #173.
