### ISSUE TITLE
Add switch commitments to grin

### ISSUE THREAD

**Issue by yeastplume** [ignopeverell/grin#177]
The functionality to allow this has been added back to our libsecp fork. Is it okay to blast ahead and extend the output format in grin with the additional switch commit? For reminder an output will become:

(vG + bH),BLAKE2(bJ)

It occurs to me that since we're using blake2, there is some leeway in how large we want to make the switch portion of the output. It could be either the same size as the pedersen commit (33 bytes) or smaller if we want to save space. How small a size could we get away with, reasonably?

**Comment by ignopeverell** [comment]
Good question. I think we can get away with 20 bytes easily.

**Comment by yeastplume** [comment]
Done in https://github.com/ignopeverell/grin/pull/179
