### ISSUE TITLE
Alternatives to Freenode IRC?

### ISSUE THREAD

**Issue by tansver** [ignopeverell/grin#19]
I am interested in this project but freenode just is not that great for connecting via tor. I see you guys have a mailing list which is awesome too but is not very active it seems? Would i2p irc maybe be a better alternative for dev talk? Wonder what you guys think about this.

**Comment by kanzure** [comment]
IIRC, freenode has re-enabled tor connectivity sometime in 2016.

**Comment by phelix** [comment]
There is https://www.oftc.net/  
Also https://gitter.im/ works both via irc and fancy webgui and at least a while ago allowed Tor.

**Comment by gellert-grindelwald** [comment]
@kanzure, It requires generating a client certificate and then registering that certificate on Freenode while not connected to tor. So it is kind of worthless. Maybe there are better options. I will look into it a bit more. In the meantime the mailing list is a great idea.

**Comment by ignopeverell** [comment]
We have a gitter since the end of October:

https://gitter.im/grin_community/Lobby

My first plan was to move to IRC as soon as I got access but I'm starting to reconsider. If enough prefer gitter I'm fine sticking with that.

**Comment by gellert-grindelwald** [comment]
@ignopeverell, Gitter is not too bad. It uses a lot of javascript which is incredibly annoying, but I can get used to it.

**Comment by gellert-grindelwald** [comment]
Ok, finally got tor connections to work for freenode. It took a lot of fiddling with different proxies, but everything is working now. Gitter is still ok, but I would rather stick to IRC now. If anyone else is having problems connecting to freenode over tor just let me know and I can help you out.

**Comment by tansver** [comment]
hmmm OK i will look into gitter thanks all for you help
