### ISSUE TITLE
Minimum fee constraint

### ISSUE THREAD

**Issue by ignopeverell** [ignopeverell/grin#26]
Design a simple fee calculation aimed at making spam as expensive as possible while keeping transactions cheap for normal users. Should likely be a mix of a fixed fee for each output (bandwidth consumed) plus a penalty for creating more UTXOs than consumed. Possibly a bonus for destroying UTXOs as well, but careful there. Enforce in the transaction pool.

**Comment by navtsi0479** [comment]
just subscribed - how divisible is grin ?

**Comment by bitcoinbilly** [comment]
Just subscribed - is grin divisible ?

**Comment by bitcoinbilly** [comment]
This design ; it balances band ore at full power consume the whole band or relative stable
    It agrees that old utxo are nicer to spend because of shortening chain but it will counterbalance fees     to cheeper for more recent utxo when the moving average isn't moving average. 
It balances utxo size with utxo place in the chain (but thatsnot that great ) 

$
1000 is the number of acount 
size /375(x1) UTXO lower up - section 2
size /315(x2)  UTXO higher up +section 4 
size /250x(3)  UTXO lower up - section 2 
size /60(x4)  UTXO higher up + section 3      (most valuable) gets the lowest fee)
fee      layer   sector
depth  layer   sector
size      layer   sector
sector   sector   

$
When a sector size is full  -utxo moves and  sector values can be enforced in The transaction pool 
You could introduce a moving average where a transaction pool needs to maintain some sector sizes 
to avoid usage of middle sectors and adjusting fee's to the outher sectors .

$
extra -  the transaction pool holds 2 datasets
            the highest and lowest UTXO and devides the size into 4
            2 is the oldest block wit oldest utxo
            1 is the youngest block with utxo 

Ok Good night :)

**Comment by JohnnSebastian** [comment]
.

**Comment by JollyMort** [comment]
Maybe this research on Monero fees would interest you: https://github.com/JollyMort/monero-research/blob/master/Monero%20Dynamic%20Block%20Size%20and%20Dynamic%20Minimum%20Fee/Monero%20Dynamic%20Block%20Size%20and%20Dynamic%20Minimum%20Fee%20-%20DRAFT.md
