### ISSUE TITLE
Ensure new coins can't be spent for X blocks

### ISSUE THREAD

**Issue by ignopeverell** [ignopeverell/grin#27]
We need to prevent miners from being able to spend their reward for enough blocks so that they can't benefit from forking the chain. A sensible default may be 1000 blocks, which would be 10 times Bitcoin's (given that our block time is 1/10th).

**Comment by JohnnSebastian** [comment]
i have been staring at the code for a while now ...
   do you follow a grand design ?

**Comment by ignopeverell** [comment]
First part of this implemented in 38d5d67e, by explicitly flagging coinbase outputs.

**Comment by antiochp** [comment]
Question about this -
I see we have `OutputFeatures` (for txn outputs) and `KernelFeatures` for (txn kernels), identifying an output and a transacton that spends a coinbase.
What stops these bits being modified or altered during use? If a miner simply flipped the "this is a coinbase" bit then would this not defeat any attempt at preventing it from being spent?

Would signing the `features` alongside the `fee` on a transaction eliminate this?

**Comment by ignopeverell** [comment]
A miner can't mess with these bits without invalidating the coinbase sums of outputs and kernels:

https://github.com/ignopeverell/grin/blob/master/core/src/core/block.rs#L418

If you want to convince yourself of it, adding a unit test would be great :-)

**Comment by antiochp** [comment]
I see some discussion around a possibly related idea in #25? 

Feels like these two requirements "prevent spending of coinbase for n blocks" and "time locked transactions" may be examples of a more generalized solution somehow - like tracking a "minimum block height before spendable" on outputs of a transaction. Maybe every transaction has this (and normally this is the current block height)?

**Comment by antiochp** [comment]
Ah got it - on the block containing the coinbase itself we check that the coinbase output (presumably a single output normally?) and the coinbase transaction kernels are all consistent.

I think my question was poorly written - I'm thinking more in terms of what happens when that coinbase output becomes an input into a subsequent transaction, say in the next block vs. 1001 blocks later.
My initial rough idea was to track the features on the input itself, based on the features from the underlying output. There would be nothing to prevent these bits from being modified though or am I missing something?

(And yes a unit test here is something I'd definitely like to put together to convince myself of some of this...)

**Comment by ignopeverell** [comment]
No, you have to track the features on the output the input is referencing. If the output is a coinbase, then you check the block distance.

**Comment by antiochp** [comment]
Throwaway spike/experiment PR up here - https://github.com/antiochp/grin/pull/1
@ignopeverell wondering if you had thoughts on what I am attempting here. 

This is more playing around to get a better feel for the various data structures in grin than a real attempt at solving this issue but I would appreciate any feedback you have?

**Comment by ignopeverell** [comment]
This looks like it's going the right way. As your comment indicates, it needs to be merged with get_unspent somehow as the current brute-force lookup block by block and output by output definitely won't perform very well. We may need to tweak the storage structure a little to have that information readily available.

Also, not sure if you haven't come around it yet, but similar validation will need to be done on block outputs.

**Comment by antiochp** [comment]
In terms of the storage structure  - are we opposed to swapping out the `Vec<Input>` and `Vec<Output>` and using `HashMap<Commitment, Input>` and `HashMap<Commitment, Output>` (on both `Block` and `Transaction`)?
This may not be the ideal long term solution but medium term it will make the lookups by commitment more reasonable.

**Comment by ignopeverell** [comment]
I was thinking about database storage structure. Loading all blocks backward from storage is still going to be a lot more expensive than an in-memory iteration. Maybe commitment to block header hash entries in rocksdb?

**Comment by ignopeverell** [comment]
Correct on everything.

**Comment by antiochp** [comment]
PR up for adding (and using) `get_block_header_by_input_commitment()` - #104 (for discussion)

**Comment by antiochp** [comment]
Reworked the previous spike based on better understanding - antiochp/grin#3
Any additional feedback would be much appreciated.

I think this covers this rule when adding new transactions via `add_to_memory_pool`.
I *think* `validate_block` in pipe.rs is where I need to be looking to do the same thing for blocks themselves - let me know if my thinking is wrong here.

Also need to make sure we have decent test coverage around this.

**Comment by antiochp** [comment]
@ignopeverell 
Couple of questions about outputs and commitments - 

The block reward is currently hard-coded to `1_000_000`.
For a given miner `reward_key` - every coinbase output for every block mined will have the same commitment - is my understanding correct here?
i.e. if a miner reuses a private key then an identical commitment is generated?

This has surfaced in a couple of places while adding test coverage for #111 - 

1) in `block::compact()` we appeared to be actually compacting away coinbase outputs and inputs if we attempted to spend a coinbase output (the input commitment matched the output commitment)
I believe I have fixed this by excluding coinbase inputs/outputs from the compact logic.
See https://github.com/ignopeverell/grin/pull/111/files#diff-dd827c758488146ce2a4f07e8bab6a26R324

2) this is the bigger issue I think - if every coinbase output for every block mined against a given reward_key has an identical commitment - we have no way of knowing how old a coinbase output is (we index the block header in the store by commitment)
Each new coinbase output effectively overwrites the previous one in the index (and it never gets old enough to mature as far as the current logic is concerned)

**Comment by ignopeverell** [comment]
Yes, we *really* want to enforce each commitment to be unique. Otherwise this can create a few headaches, like the ones you mention. And we generally don't want people to reuse keys for even more reasons than in Bitcoin.

**Comment by antiochp** [comment]
So in the tests do we just want to use a unique `reward_key` for each mined block and assume this is being enforced elsewhere, at least for now?

**Comment by antiochp** [comment]
Also looking through the code - I see `check_duplicate_outputs` is used to actually enforce this from the transaction point of view.
So maybe we need to do something similar with coinbase outputs on a block itself - as I don't think this is prevented currently for coinbase outputs.

**Comment by ignopeverell** [comment]
Yes, just assume it's in there for now. It will actually be enforced by what I'm working on right now: the UTXO sum tree.

**Comment by antiochp** [comment]
This should be resolved by #111
