### ISSUE TITLE
simulnet test case runs infinitely

### ISSUE THREAD

**Issue by greole** [ignopeverell/grin#31]
The test case `simulnet.rs` is stuck at

```
  evtlp.run(change(&servers[4]).and_then(|tip| {
    assert!(tip.height == original_height+1);
    Ok(())
  }));
```
and never finishes.  I am running rustc 1.14.0 (e8a012324 2016-12-16).

**Comment by ignopeverell** [comment]
The test forces a smaller size for cuckoo cycle but the genesis block proof of work wasn't recomputed, leading to a wrong total difficulty calculation. Should be better now. The test still takes several seconds as it does a few proof of work computations.
