### ISSUE TITLE
Reduction of security by removing (input|output) pairs across blocks

### ISSUE THREAD

**Issue by cupnoodlegirl** [ignopeverell/grin#33]
It is interesting to remove (input|output) pairs across blocks and the blockchain size is well compacted as a result. This is good. 

However, block validation is insufficient in compacted blockchain because following conditions are not satisfied.
1) Input, output values and excess value in a transaction sum to zero (transaction consensus rule)
2) Input, output and excess values in a block sum to zero (block consensus rule)
3) All outputs being spent have valid rangeproofs. (transaction consensus rule)
In 1), we cannot check that a transaction sums to zero if inputs or outputs are removed.
In 2), we cannot check that a block sums to zero if inputs or outputs are removed.
In 3), we cannot check that removed inputs/outputs have valid amounts.

Therefore, I think It leads to security reduction (like SPV security in Bitcoin).
What do you think about that? I would appreciate any reply.

**Comment by ignopeverell** [comment]
Actually all 3 of your statements can be checked because:

1. Cut-through can only be done on identical commitments between input and output.
2. A negative value cannot be cut-through.

The first assertion covers your 2 first points, the second assertion covers your third.

**Comment by cupnoodlegirl** [comment]
@ignopeverell 
Thanks.

Your assertion seems to place the assumption that connected peer from you follows blockchain consensus rule correctly.
For example, consider that you are a new node and connect to some peers and try to download and validate the compacted blockchain.
Neighbors can send you the compacted blockchain which contains a invalid commitment(i.e. negative amount) cut from the blockchain if they are adversary. 
New node cannot fully validate the compacted blockchain received from neighbors **by itself**.

**Comment by ignopeverell** [comment]
Neighbors cannot fake just a single UTXO as it would invalidate the whole sum of blinding factors. In the scenario you describe the whole UTXO set would have to be fabricated, which is fairly trivial to detect. One addition we have is a UTXO root hash in every block header for example, which makes it simple to detect such attacks.

Note that bitcoin is just as sensitive to such a "sybil at bootstrap" attack. The point is sooner or later, the new node will discover the more worked chain as long as it connects to at least one honest node.
