### ISSUE TITLE
Replace AsFixedBytes<T> with AsRef<T>

### ISSUE THREAD

**Issue by Latrasis** [ignopeverell/grin#34]
Since [`AsRef`](https://doc.rust-lang.org/std/convert/trait.AsRef.html) already exists within the standard library, it would make sense to use it instead of adding another trait.

**Comment by ignopeverell** [comment]
The trait AsFixedBytes adds the requirement that structs implementing it must be fixed size. Implementing it for a struct with a &[u8] representation of variable size would violate the trait. Maybe it would be better expressed in terms of AsRef forcing Sized though.

**Comment by Latrasis** [comment]
I assume if the `Sized` constraint is added to the `Writer::write_fixed_bytes` method, that may work?
