### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [ignopeverell/grin#46]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by Latrasis** [comment]
If #44 goes well, we should be moving from `rustc-serialize`/`serde` to using tokio codecs

**Comment by dtolnay** [comment]
Amazing! Thanks for the update. Feel free to close this if that work is already tracked elsewhere.

**Comment by ignopeverell** [comment]
Addressed by PR #44. Thanks for creating an issue still!
