### ISSUE TITLE
Style questions

### ISSUE THREAD

**Issue by merope07** [ignopeverell/grin#5]
Is there a consistent spacing style we should target for this project? It seems like macros have 2-space tabs, most of the code uses tabs, there is some 4-space tabs, and the dependencies use 4-space tabs (which is standard in the Rust community).

I also don't sit well with `Option<Error>`. The "silly" `Result<(), Error>` lets you write `Ok(())` which looks funny but has the word "ok" in it. Receiving `None` and interpreting this as "ok" is confusing at first.

I don't want to step on any toes here, but it would be good to agree on these things and have them written down somewhere.

**Comment by merope07** [comment]
Ok, I see from recent commits there's an effort to standardize on tabbing, so I'll do that.

However, I still think using `None` for "ok" is bad style, because it inverts the expected meaning of [`and` and `or`](https://doc.rust-lang.org/std/option/enum.Option.html#method.and) compared to `Result`.

**Comment by ignopeverell** [comment]
Sorry for mixed tabbing, was likely caused to mixing configurations on my end.

I've been on the fence about Option<Error> and I seem to be on the wrong side of that fence as to what's more or less standard in most Rust libraries. So let's revert to Result<(), Error>.

**Comment by merope07** [comment]
Thank you!
