### ISSUE TITLE
Transition core::Hash to use Encoder

### ISSUE THREAD

**Issue by Latrasis** [ignopeverell/grin#52]
In continuation of #51 and #39, currently `core::hash` depends on `Writeable`/`Readable` traits. These include: `Hash`, `HashWriter` and `Hashed`. Current agenda is to:

* Collect all requirements that the current `core::hash` module fulfills
* Propose minimum changes needed to use with `Encoder` with minimum trimming.

I think once we have a working proposal, we will have more flexibility on what can be refactored and trimmed.

**Comment by Latrasis** [comment]
Looking into this further, I'm thinking we may need to move the `store::codec` to `core`. Otherwise we get recursive dependencies.

**Comment by ignopeverell** [comment]
I was thinking the same, it would also make more sense there.

**Comment by Latrasis** [comment]
Closing based on #39
