### ISSUE TITLE
Implement Rate Limiting

### ISSUE THREAD

**Issue by Latrasis** [ignopeverell/grin#55]
From #54: 
> For DoS protection the first rule should be rate limiting based. No peer should send us more than X MB per second and we shouldn't send more (assuming it was all requested) than Y MB per second to any peer either. We can start with X=200 and Y=100. That should be measurable at the protocol or connection level easily.

* [x] Implement memory throughput counter for each peer connection
* [x] Setup tests for rate limits

**Comment by Latrasis** [comment]
@ignopeverell: For testing, any pointers for mocking nodes that spam too much but valid data?

**Comment by ignopeverell** [comment]
* The easiest is probably using the PeerAddrs message (when a peer sends the list of peers it knows to another peer). See: https://github.com/ignopeverell/grin/blob/master/p2p/src/protocol.rs#L200
* What do you mean by "handled"? How to implement them? Maybe a per-second counter?
