### ISSUE TITLE
Project not building with gcc 7+

### ISSUE THREAD

**Issue by yeastplume** [ignopeverell/grin#61]
It seems the dependency librocksdb-sys v0.4.1 has issues compiling its own rocksdb dependency on gcc7+ with issues such as the following:
```
cargo:warning=                 from rocksdb/db/auto_roll_logger.h:15,
cargo:warning=                 from rocksdb/db/auto_roll_logger.cc:6:
cargo:warning=rocksdb/util/thread_local.h:66:16: error: ‘function’ in namespace ‘std’ does not name a template type
cargo:warning=   typedef std::function<void(void*, void*)> FoldFunc;
```
It seems to be directly related to this issue, which was fixed within rocksdb:

 #https://github.com/facebook/rocksdb/issues/1492

However the actual librocksdb rust bindings haven't been updated since, causing the whole build to fail.

I've opened an issue for the maintainers here, you might want to watch this and come up with an alternate strategy if they've gone missing:

#https://github.com/spacejam/rust-rocksdb/issues/122

**Comment by ignopeverell** [comment]
Can you try an upgrade to rust-rocksdb 0.7.0? Was released yesterday and looks like it has an update of rocksdb to a much more recent version.

**Comment by yeastplume** [comment]
Yes, 0.7.0 seems to work fine now. I'll include it in next PR if someone else doesn't change it first.
