### ISSUE TITLE
Document grin's proof of work

### ISSUE THREAD

**Issue by ignopeverell** [ignopeverell/grin#67]
Should include a little bit on Cuckoo Cycle but also how we use it (with another layer of hashing), the format in block headers and the difficulty algo.

**Comment by yeastplume** [comment]
I'm starting to poke around the pow implementation now to actually exercise the testing functions I've put together, so I'll try and document as I go.

**Comment by yeastplume** [comment]
Start is in here: (From PR #69) 

https://github.com/yeastplume/grin/blob/mining-testing/doc/pow/pow.md

**Comment by tromp** [comment]
The current write-up is wrong is several places. The nodes in Cuckoo Cycle do not store any values. They're just numbered 0,2,4,6,... on the even side and 1,3,5,7,... on the odd side. More confusingly, the write up mixes up cycles and paths. Cuckoo Cycle does not look for paths.

**Comment by yeastplume** [comment]
@tromp Thank you, updated understanding and doc accordingly. Would you mind having a look at the updated version on https://github.com/yeastplume/grin/blob/doc-updates/doc/pow/pow.md and let me know if this is more accurate?

**Comment by tromp** [comment]
On Mon, Jul 3, 2017 at 11:49 AM, Yeastplume <notifications@github.com> wrote:
> @tromp Thank you, updated understanding and doc accordingly. Would you mind
> having a look at the updated version on
> https://github.com/yeastplume/grin/blob/doc-updates/doc/pow/pow.md and let
> me know if this is more accurate?

Yes, it's more accurate. But as long as we're nitpicking...

The name of the PoW is "Cuckoo Cycle" in singular, not the plural
"Cuckoo Cycles".

A bipartite graph is one in which edges go only between 2 groups of nodes.

Cuckoo Cycle fixes M at N/2, which limits the number of cycles to a few at most.

The siphash function creates only one endpoint of an edge. You use 2
invocations to get both endpoints (one with 2*edge_index, and the
other with 2*edge_index+1, as input).

Thanks for taking this into account.

regards,
-John

**Comment by yeastplume** [comment]
Okay, thanks again, I've put these clarifications in and will PR a new version.

**Comment by ysangkok** [comment]
For future reference, updated version seems to be here: https://github.com/yeastplume/grin/blob/master/doc/pow/pow.md

**Comment by ignopeverell** [comment]
@yeastplume could you create a PR for your doc updates? Thanks!

**Comment by yeastplume** [comment]
It was already merged here: https://github.com/ignopeverell/grin/pull/73 ... I haven't changed it since.

**Comment by ignopeverell** [comment]
Oh ok, my bad, I should have double-checked. If there are no objections, I'll close this issue.

**Comment by yeastplume** [comment]
No, no worries. I think this can be safely closed if you're happy with the contents. I'll probably update the doc as things evolve, but I think there's enough there now to sate curious onlookers.
