### ISSUE TITLE
Is Cuckoo really a good idea?

### ISSUE THREAD

**Issue by Kixunil** [ignopeverell/grin#75]
In famous article about ZCash Peter Todd [analyses Equihash PoW](https://petertodd.org/2016/cypherpunk-desert-bus-zcash-trusted-setup-ceremony#equihash-proof-of-work). It seems like Equihash and Cuckoo are similar in trying to constrain mining by memory latency ("comodity DRAM"). So at least the part about specialized memory chips probably applies to Cuckoo as well.

**Comment by mochacoder** [comment]
Well the article mentions a few times how Tromp was able to show how Equihash wasn't as good as originally thought:

> However, as of writing Tromp has managed to get memory requirements down to just 144MiB! The Equihash paper predicted that kind of optimization would incur a multiple orders of magnitude penalty… not a good sign.

> For example, Tromp has reported good equihash performance on NVIDIA GTX980 GPU, which as of writing has a retail cost of about $500 USD and comes with 4GiB of GDDR5 DRAM; if Equihash really works as intended, the cost of that RAM should dominate hashing costs.

And Tromp is the guy who created Cuckoo so I'm assuming he is improving on Equihash's shortcomings.

**Comment by Kixunil** [comment]
Yes, I know. I was mostly referring to [specialized memory chips](https://petertodd.org/assets/2016-11-14/hbm.png)/[High Bandwidth Memory (HBM)](https://en.wikipedia.org/wiki/High_Bandwidth_Memory).

**Comment by apoelstra** [comment]
Cuckoo is limited by memory latency vs equihash which is limited by memory bandwidth.

**Comment by Kixunil** [comment]
@apoelstra thanks for explanation!
