### ISSUE TITLE
CI testing mode and testing speed

### ISSUE THREAD

**Issue by yeastplume** [ignopeverell/grin#85]
From discussions and recent issues with the test suite, it's clear that a solution is needed to reduce the time it takes for tests to run, and it should probably be a project goal to keep automated testing time to a minimum.

It's clear at the moment that the biggest issue is mining speed, as a lot of tests build up a blockchain from scratch in order to test the results. In tests where the mining itself isn't the focus, there should be a mode that builds up blockchains very quickly using cuckoo parameters tweaked to have them build as fast as possible using the internal miner.

To address this, I propose:
-Changing the test_mode parameter from a boolean to an enum, with values along the lines of (CI, USER_TESTING, PRODUCTION)
-Associating tweakable parameters with the enum, i.e. cuckoo_size and solution size, collecting the values currently in consensus.rs into there, (as a matter of fact I'd remove TEST_SIZESHIFT and testing stuff from consensus.rs and only leave actual consensus values in there, reading cuckoo params from elsewhere if test_mode!=production)
-Using the values from the enum in every point in the code that references cuckoo mining.

**Comment by ignopeverell** [comment]
Sounds like a good plan.
