### ISSUE TITLE
Mining/POW/Cuckoo Refactor

### ISSUE THREAD

**Issue by yeastplume** [ignopeverell/grin#97]
At the moment, the code related to proof of work, cuckoo itself, and mining are sprinkled throughout the code. The POW verification and internal cuckoo miner is in a subdirectory of core, the cuckoo-miner integration code is in grin/grin, mining the genesis block is called from chain and is stuck using the internal miner which can't use the cuckoo-miner code in grin/grin because it would lead to a circular (and unwanted) dependency... mining config is in grin/grin, and I've had to stick in a messy global into core so that all modules that use POW in any way can use consistent parameters.... and so forth... it's leading to a lot of inconsistency and cruft in the code.

To address these issues, I propose moving all of the POW/Cuckoo/Mining/Plugin-Integration and Validation code into a separate crate/module called 'pow', and refactoring all of the code that uses it to remain as POW agnostic as possible. This way, the genesis block can be modified and mined in the same way as all other blocks, and any future changes to POW are localised and encapsulated. I'll also be able to move the values in global.rs into the new pow module, cleaning that up somewhat.

**Comment by yeastplume** [comment]
Thinking more, since pow operations need to serialise and hash, this would also mean moving the generic data operations out of core and into their own package (to avoid core and pow depending on each other). As it would turn out core would need to depend on pow for the Proof, Target and Difficulty structs, which pow would need core for ser.rs and hash.rs. If hash.rs and ser.rs were moved into a separate crate, core would rely on pow, while pow and core would rely on the new crate (pmmr and sumtree would probably belong there, as they define operations on data instead of necessarily MW-specific definitions). Then core would be dedicated solely to grin/MW specific definitions (Transactions/Block definitions).

May be going a few steps too far here... let me know your thoughts

**Comment by yeastplume** [comment]
Okay, sorry for train-of-thought spam but I've played around with this and realised I'm way overthinking it; it should be a simple refactor.

All I want to do is move pow from core/pow into its own crate under the project root, and then move the plugin and mining code from grin/grin into the new pow crate. Then we should be able to mine the genesis block using cuckoo-miner from chain, and core isn't contaminated with cuckoo-miner configuration and higher-level concerns that should stay out of there.

**Comment by ignopeverell** [comment]
Yes, that latest option makes sense to me.I think Proof, Target and Difficulty can remain in core (which they are) but moving all mining-related code in its own crate totally makes sense.

**Comment by yeastplume** [comment]
Think we're good here now
